@startuml
IVending <|
Produkttyper <|-- Dricka
Produkttyper <|-- Mellanmål
Produkttyper <|-- Choklad
Produkttyper <|-- Leksak
Leksak       <|-- Lego
@enduml

# Local Variables:
# compile-command: "/usr/bin/plantuml -tpng ./ivending.plantuml"
# End:
