@startuml
left to right direction
actor Kund     as k
package Varuautomat {
  usecase "Mata in kontanter"      as mata_in_kontanter
  usecase "Välj produkt"           as välj_produkt
  usecase "Produkt lämnas ut\nom tillgänglig"      as produkt_matas_ut
  usecase "Slutför transaktionen"  as slutför_transaktionen
  usecase "Återfå växel"           as återfå_växel
  usecase "Enbart i fasta valörer" as enbart_hela_valörer_hanteras
  usecase "Mata in mynt"           as mata_in_mynt
  usecase "Mata in sedlar"         as mata_in_sedlar
  usecase "Saldo debiteras"        as saldo_debiteras
  usecase "Saldo krediteras"       as saldo_krediteras
}
k --> (mata_in_kontanter)
mata_in_kontanter	<|-- mata_in_mynt
mata_in_kontanter	<|-- mata_in_sedlar
mata_in_kontanter      .> saldo_krediteras : include
k --> (välj_produkt)
k --> (slutför_transaktionen)
(mata_in_kontanter) .>     (enbart_hela_valörer_hanteras) : include
(välj_produkt) .>          (produkt_matas_ut) :include
(produkt_matas_ut) .>      (saldo_debiteras) :include
(slutför_transaktionen) .> (återfå_växel) : include
(återfå_växel) .>          (enbart_hela_valörer_hanteras) : include
(återfå_växel) .>          (saldo_debiteras) :include
@enduml
